const vietnamBanks = [
    { code: "VCB", name: "Vietcombank" },
    { code: "BIDV", name: "BIDV" },
    { code: "CTG", name: "VietinBank" },
    { code: "VBA", name: "Agribank" },
    { code: "TCB", name: "Techcombank" },
    { code: "MB", name: "MB Bank" },
    { code: "ACB", name: "ACB" },
    { code: "VPB", name: "VPBank" },
    { code: "TPB", name: "TPBank" },
    { code: "STB", name: "Sacombank" },
    { code: "HDB", name: "HDBank" },
    { code: "VIB", name: "VIB" },
    { code: "EIB", name: "Eximbank" },
    { code: "MSB", name: "MSB" },
    { code: "OCB", name: "OCB" },
    { code: "SHB", name: "SHB" },
    { code: "LPB", name: "LPBank" },
    { code: "SEAB", name: "SeABank" },
    { code: "ABB", name: "ABBank" },
    { code: "BVB", name: "BaoViet Bank" },
    { code: "NAB", name: "Nam A Bank" },
    { code: "VCCB", name: "Viet Capital Bank" },
    { code: "PGB", name: "PGBank" },
    { code: "NCB", name: "NCB" },
    { code: "KLB", name: "KienlongBank" },
    { code: "SGB", name: "Saigonbank" },
    { code: "VAB", name: "VietABank" },
    { code: "BAB", name: "Bac A Bank" },
    { code: "BCA", name: "CBBank" },
    { code: "IVB", name: "Indovina Bank" },
    { code: "CIMB", name: "CIMB Vietnam" },
    { code: "VRB", name: "Vietnam-Russia Bank" },
    { code: "WVN", name: "Woori Bank Vietnam" },
    { code: "SCB", name: "SCB" },
    { code: "SHINHAN", name: "Shinhan Bank Vietnam" },
    { code: "STANDARD", name: "Standard Chartered Vietnam" },
    { code: "HSBC", name: "HSBC Vietnam" },
    { code: "UOB", name: "UOB Vietnam" },
    { code: "DBS", name: "DBS Vietnam" },
    { code: "CITIBANK", name: "Citibank Vietnam" },
];

export default vietnamBanks;